package tengr.models;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * An entity Account composed by three fields (id, login, password, status).
 * The Entity annotation indicates that this class is a JPA entity.
 * The Table annotation specifies the name for the table in the db.
 *
 * @author tengr
 */
@Entity
@Table(name = "accounts")
public class Account {

  // ------------------------
  // PRIVATE FIELDS
  // ------------------------
  
  // An autogenerated id (unique for each account in the db)
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private long id;

  // The account's login
  @NotNull
  private String login;

  // The account's password
  @NotNull
  private String password;
  
  // The account's status
  @NotNull
  private String status;
  

  // ------------------------
  // PUBLIC METHODS
  // ------------------------
  
  public Account() { }

  public Account(long id) { 
    this.id = id;
  }
  
  public Account(String login, String password, String status) {
    this.login = login;
    this.password = password;
    this.status = status;
  }

  // Getter and setter methods
  public long getId() {
    return id;
  }

  public void setId(long value) {
    this.id = value;
  }

  public String getLogin() {
    return login;
  }

  public void setLogin(String value) {
    this.login = value;
  }

  public String getPassword() {
    return password;
  }
  
  public void setPassword(String value) {
    this.password = value;
  }

  public String getStatus() {
    return status;
  }
  
  public void setStatus(String value) {
    this.status = value;
  }

  
} // class Account
